### ISSUE TITLE
I don't know how to do it？ help me

### ISSUE THREAD

**Issue by ytgcljj** [rauwuckl/ros_simple_follower#1]
Hello, I don't see the mistake now, but the car doesn't work
1、Here is the laser rostopic list
nuc16@nuc16desktop:~$ rostopic list
/diagnostics
/lslidar_packet
/lslidar_point_cloud
/lslidar_sweep
/rosout
/rosout_agg
/scan
2、Here is the laser_follower.launch
/cmd_vel/yolo
/hokuyo_base/scan
/joy
/object_tracker/current_position
/object_tracker/info
/rosout
/rosout_agg

**Comment by rauwuckl** [comment]
Hi, I don't actually have any access to a robot (or ros) at the moment and it's been a year but lets see if we can figure this one out:

when you run rostopic list you see way to few topics. The real summit xl has way more topics. Apparently you are running it on your desktop. Can you try logging into the car computer with ssh and run rostopic list there. You should see way more topics.

Then to make the thing work you either have to run this follower node on the summit's board computer (install it there, ssh into it and run it). Or you have to make  your desktop use the summits board computer as its ros master.:
http://wiki.ros.org/ROS/Tutorials/MultipleMachines (this might help)

let me know how it goes
